# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neibas', '0002_neiba_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neiba',
            old_name='first_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='neiba',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='neiba',
            name='email',
        ),
        migrations.AddField(
            model_name='neiba',
            name='population',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
